language: ruby
rvm:
  - "2.0.0" 
env: TEST_DATABASE_URL=postgres://postgres@locahost/travispopup RAILS_ENV=test AWS_ACCESS_KEY_ID=fake AWS_SECRET_ACCESS_KEY=fake AWS_BUCKET=fake IA_ACCESS_KEY_ID=fake IA_SECRET_ACCESS_KEY=fake SECRET_TOKEN=fakefakefakefakefakefakefakefakefakefakefakefakefakefakefakefake STRIPE_SECRET_KEY=fakerfakerfaker STRIPE_PUBLISHABLE_KEY=fakerfakerfaker EMAIL_USERNAME=edison@popuparchive.org DEVISE_SECRET_KEY=fakefakerfakest EMAIL_FROM='Pop Up Archive <edison@popuparchive.com>' CLOUDFRONT_KEY='"-----BEGIN RSA PRIVATE KEY-----\nMIICXgIBAAKBgQvLG9hu4a4UYPmMQSQOgyAonuQUXSGLktJ8665vV9BCNfP1JSLr\nF6yQMQdRhF6vwDng9r8vLdToMhmNAey2qXk8H2FiI+k3RBm4pX69r15jUEw+anKq\nRJtSFNI3MrWcTAAokrBTmkBHkp/ml/n7dfg14sCK2v7atcCO/KYWF3q4MQIDAQAB\nAoGBBe5gUrlxRtt46ghfuoKR79p+DrcvH2/Sp4mr/k6BG3wxJkBkLOuPPHpILiYR\nLI23X2SEtCJGKo2cpL0F+sbi9NKQck32Pluldqd9ErKq55kWoYSxYdvw0KWMxJkK\n5rIXWm7/LCjgSfgQpNsMszv61S5cKtrQ5qsbQgZjhG8Ik3cBAkEDvW1ISpZu+XYz\nME/1PT7kpifm/6cgKGnQ7O50jS9JTQHx+mPX/JZcZ9ESQOm3PsfcpTUuvh+WxSxZ\nNWAskyFRCwJBAydCZ5OirKxsPng13lYVBmIbLoJbGCHP5tSMefORx9OmLfIPhvPD\nFLdCT7rd/kP61x4IMuMyzpy3vTERkuw4mTMCQQM+2txWZg/uCoZHkcvnl3HDQ3Ny\nPm1oxNNbGWApuXRqEJsWSJkCCNYt/cBSdr/gCn9PG0TyFuW3PFI6QLjOAaabAkEC\nr0xUT1hzV6IZVdPXZscj1id6Y7YXR8Jwr4qi0gPOdJ7KA4vAxI3Vd2nX5CvZrhtF\nR+aHHPVHABtX0w05YDGYDQJAM6cdORylBiXKZxCvU85hG0ey8sUqIq3L8hlzmIw6\nCkFrsYSjefmLHe+7cNbf3agjCCUZp6wkXko4KO6D5jZQMg==\n-----END RSA PRIVATE KEY-----"' CLOUDFRONT_KEY_PAIR_ID=ee08PiqM9XAP3Q8c2vAzPTjZyB7BjxJJ
before_script:
  - bundle exec rake db:create db:migrate
bundler_args: --retry 5 --without development assets 
services:
  - elasticsearch
  - redis-server
notifications:
  email:
    - popuparchive-dev@googlegroups.com
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev
  - travis_retry gem update --system
  - travis_retry gem install bundler --pre
  - gem --version
  - bundle --version
  - ln -s /usr/share/elasticsearch/bin/elasticsearch.in.sh ~/.elasticsearch.in.sh
